name: CI

on:
  pull_request:
  push:
    branches:
      - master
env:
  GO111MODULE: on
  GORMUNGANDR_DOCKERTEST_TAG: navitia_builder

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install libzmq3
        run: |
          sudo apt update
          sudo apt install libzmq3-dev

      - name: Retreive mock kraken
        run: docker pull navitia/mock-kraken:${GORMUNGANDR_DOCKERTEST_TAG}

      - name: Install all the build and lint dependencies
        run: make setup

      - name: Install linter
        run: make linter-install

      - name: Run all the tests and code checks
        run: make ci
